require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe FacultiesController do

  # This should return the minimal set of attributes required to create a valid
  # Faculty. As you add validations to Faculty, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # FacultiesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all faculties as @faculties" do
      faculty = Faculty.create! valid_attributes
      get :index, {}, valid_session
      assigns(:faculties).should eq([faculty])
    end
  end

  describe "GET show" do
    it "assigns the requested faculty as @faculty" do
      faculty = Faculty.create! valid_attributes
      get :show, {:id => faculty.to_param}, valid_session
      assigns(:faculty).should eq(faculty)
    end
  end

  describe "GET new" do
    it "assigns a new faculty as @faculty" do
      get :new, {}, valid_session
      assigns(:faculty).should be_a_new(Faculty)
    end
  end

  describe "GET edit" do
    it "assigns the requested faculty as @faculty" do
      faculty = Faculty.create! valid_attributes
      get :edit, {:id => faculty.to_param}, valid_session
      assigns(:faculty).should eq(faculty)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Faculty" do
        expect {
          post :create, {:faculty => valid_attributes}, valid_session
        }.to change(Faculty, :count).by(1)
      end

      it "assigns a newly created faculty as @faculty" do
        post :create, {:faculty => valid_attributes}, valid_session
        assigns(:faculty).should be_a(Faculty)
        assigns(:faculty).should be_persisted
      end

      it "redirects to the created faculty" do
        post :create, {:faculty => valid_attributes}, valid_session
        response.should redirect_to(Faculty.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved faculty as @faculty" do
        # Trigger the behavior that occurs when invalid params are submitted
        Faculty.any_instance.stub(:save).and_return(false)
        post :create, {:faculty => {}}, valid_session
        assigns(:faculty).should be_a_new(Faculty)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Faculty.any_instance.stub(:save).and_return(false)
        post :create, {:faculty => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested faculty" do
        faculty = Faculty.create! valid_attributes
        # Assuming there are no other faculties in the database, this
        # specifies that the Faculty created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Faculty.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => faculty.to_param, :faculty => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested faculty as @faculty" do
        faculty = Faculty.create! valid_attributes
        put :update, {:id => faculty.to_param, :faculty => valid_attributes}, valid_session
        assigns(:faculty).should eq(faculty)
      end

      it "redirects to the faculty" do
        faculty = Faculty.create! valid_attributes
        put :update, {:id => faculty.to_param, :faculty => valid_attributes}, valid_session
        response.should redirect_to(faculty)
      end
    end

    describe "with invalid params" do
      it "assigns the faculty as @faculty" do
        faculty = Faculty.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Faculty.any_instance.stub(:save).and_return(false)
        put :update, {:id => faculty.to_param, :faculty => {}}, valid_session
        assigns(:faculty).should eq(faculty)
      end

      it "re-renders the 'edit' template" do
        faculty = Faculty.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Faculty.any_instance.stub(:save).and_return(false)
        put :update, {:id => faculty.to_param, :faculty => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested faculty" do
      faculty = Faculty.create! valid_attributes
      expect {
        delete :destroy, {:id => faculty.to_param}, valid_session
      }.to change(Faculty, :count).by(-1)
    end

    it "redirects to the faculties list" do
      faculty = Faculty.create! valid_attributes
      delete :destroy, {:id => faculty.to_param}, valid_session
      response.should redirect_to(faculties_url)
    end
  end

end
