source 'https://rubygems.org'

gem 'rails', '3.2.15'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

gem 'nokogiri'
gem 'devise', "~> 3.1.0"
gem 'devise-encryptable'
gem "thinking-sphinx", "~> 2.0.12"
gem 'mysql2'
gem 'cancan'
gem 'gravatar_image_tag'
gem 'kaminari'
gem 'whenever'
#gem 'mathjax-rails'
gem 'exception_notification'


# for markdown rich text
gem 'redcarpet', '~> 3.0.0'
gem 'coderay', '~> 1.1.0'

group :production do
  gem 'memcache-client'
  gem 'thin'
end

group :test, :development do
  gem 'mailcatcher'
  gem 'rspec-rails', '~> 2.14.0'
  gem "factory_girl_rails", "~> 4.2.1"
  gem "shoulda-matchers"
  gem 'debugger'
  gem 'rb-fsevent'
  gem 'guard-rspec'

  gem 'spork-rails', github: 'sporkrb/spork-rails'
  gem 'guard-spork'
  gem 'childprocess'
  gem 'faker', "~> 1.1.2"
  gem 'annotate', :git => 'git://github.com/ctran/annotate_models.git'
  gem 'translate-rails3', require: 'translate'
end

group :test do
  gem "capybara"
  gem "database_cleaner", "~> 0.9.1" 
  gem "launchy", "~> 2.2.0"
  gem 'sqlite3'
  gem 'selenium-webdriver'
  gem 'capybara-webkit'
  gem 'email_spec'
  #gem 'poltergeist'
end

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'execjs'
#  gem 'therubyracer', '~> 0.11.0'

  gem 'uglifier', '>= 1.0.3'

  gem 'compass-rails'
  gem 'zurb-foundation', '~> 4.3.2'
  gem 'font-awesome-rails'
  gem 'mathjax-rails'
  gem 'premailer-rails'
  gem 'sanitize'
end

gem 'jquery-rails'
gem 'jquery-ui-rails'
gem 'savon', '~> 2.2.0'

gem 'sidekiq'

gem 'rails-i18n'
gem 'devise-i18n'
#gem 'turbolinks'

# To use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# To use Jbuilder templates for JSON
# gem 'jbuilder'

# Use unicorn as the app server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger
# gem 'ruby-debug19', :require => 'ruby-debug'
