source 'https://rubygems.org'

gem 'rails', '3.2.8'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

gem 'nokogiri'
gem 'sqlite3'
gem 'devise', '~>2.1'
gem 'devise-encryptable'
gem 'rspec-rails', :group => [:test, :development]
gem "thinking-sphinx", "~> 2.0.12"
gem 'mysql2'
gem 'cancan'
gem 'gravatar_image_tag'
gem 'kaminari'
gem 'font-awesome-rails'
gem 'whenever'
gem 'mathjax-rails'

# for markdown rich text
gem 'redcarpet', '~> 2.1.1'
gem 'coderay', '~> 1.0.7'

group :production do
	gem 'memcache-client'
  gem 'thin'
end

group :test, :development do
  gem 'mailcatcher'
  gem 'spork', '~> 1.0rc'
  gem 'guard-spork'
  gem "factory_girl_rails", "~> 3.0"
  gem "capybara"
  gem "guard-rspec"
  gem 'shoulda-matchers'
  gem 'yaml_db'
  gem 'railroady'
  gem 'debugger'
end

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  #gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'

  # See https://github.com/sstephenson/execjs#readme for more supported runtimes
  # gem 'therubyracer', :platform => :ruby

  gem 'uglifier', '>= 1.0.3'

  gem 'twitter-bootstrap-rails'

  gem 'jquery-ui-rails'
  gem 'jquery-ui-themes'
end

gem 'jquery-rails'
gem 'savon'

# To use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# To use Jbuilder templates for JSON
# gem 'jbuilder'

# Use unicorn as the app server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger
# gem 'ruby-debug19', :require => 'ruby-debug'
