                             tags_index GET    /tags/index(.:format)                                            tags#index
                                    tag GET    (/:locale)/tags/:tag(.:format)                                   groups#index {:locale=>/en|de/}
                                   tags GET    (/:locale)/tags(.:format)                                        tags#index {:locale=>/en|de/}
               groups_change_group_type GET    (/:locale)/groups/change_group_type(.:format)                    groups#change_group_type {:locale=>/en|de/}
                  announcement_comments GET    (/:locale)/announcements/:announcement_id/comments(.:format)     comments#index {:locale=>/en|de/}
                                        POST   (/:locale)/announcements/:announcement_id/comments(.:format)     comments#create {:locale=>/en|de/}
               new_announcement_comment GET    (/:locale)/announcements/:announcement_id/comments/new(.:format) comments#new {:locale=>/en|de/}
                           edit_comment GET    (/:locale)/comments/:id/edit(.:format)                           comments#edit {:locale=>/en|de/}
                                comment GET    (/:locale)/comments/:id(.:format)                                comments#show {:locale=>/en|de/}
                                        PUT    (/:locale)/comments/:id(.:format)                                comments#update {:locale=>/en|de/}
                                        DELETE (/:locale)/comments/:id(.:format)                                comments#destroy {:locale=>/en|de/}
                    group_announcements GET    (/:locale)/groups/:group_id/announcements(.:format)              announcements#index {:locale=>/en|de/}
                                        POST   (/:locale)/groups/:group_id/announcements(.:format)              announcements#create {:locale=>/en|de/}
                 new_group_announcement GET    (/:locale)/groups/:group_id/announcements/new(.:format)          announcements#new {:locale=>/en|de/}
                      edit_announcement GET    (/:locale)/announcements/:id/edit(.:format)                      announcements#edit {:locale=>/en|de/}
                           announcement GET    (/:locale)/announcements/:id(.:format)                           announcements#show {:locale=>/en|de/}
                                        PUT    (/:locale)/announcements/:id(.:format)                           announcements#update {:locale=>/en|de/}
                                        DELETE (/:locale)/announcements/:id(.:format)                           announcements#destroy {:locale=>/en|de/}
                      question_comments GET    (/:locale)/questions/:question_id/comments(.:format)             comments#index {:locale=>/en|de/}
                                        POST   (/:locale)/questions/:question_id/comments(.:format)             comments#create {:locale=>/en|de/}
                   new_question_comment GET    (/:locale)/questions/:question_id/comments/new(.:format)         comments#new {:locale=>/en|de/}
                                        GET    (/:locale)/comments/:id/edit(.:format)                           comments#edit {:locale=>/en|de/}
                                        GET    (/:locale)/comments/:id(.:format)                                comments#show {:locale=>/en|de/}
                                        PUT    (/:locale)/comments/:id(.:format)                                comments#update {:locale=>/en|de/}
                                        DELETE (/:locale)/comments/:id(.:format)                                comments#destroy {:locale=>/en|de/}
                        answer_comments GET    (/:locale)/answers/:answer_id/comments(.:format)                 comments#index {:locale=>/en|de/}
                                        POST   (/:locale)/answers/:answer_id/comments(.:format)                 comments#create {:locale=>/en|de/}
                     new_answer_comment GET    (/:locale)/answers/:answer_id/comments/new(.:format)             comments#new {:locale=>/en|de/}
                                        GET    (/:locale)/comments/:id/edit(.:format)                           comments#edit {:locale=>/en|de/}
                                        GET    (/:locale)/comments/:id(.:format)                                comments#show {:locale=>/en|de/}
                                        PUT    (/:locale)/comments/:id(.:format)                                comments#update {:locale=>/en|de/}
                                        DELETE (/:locale)/comments/:id(.:format)                                comments#destroy {:locale=>/en|de/}
                       question_answers GET    (/:locale)/questions/:question_id/answers(.:format)              answers#index {:locale=>/en|de/}
                                        POST   (/:locale)/questions/:question_id/answers(.:format)              answers#create {:locale=>/en|de/}
                    new_question_answer GET    (/:locale)/questions/:question_id/answers/new(.:format)          answers#new {:locale=>/en|de/}
                            edit_answer GET    (/:locale)/answers/:id/edit(.:format)                            answers#edit {:locale=>/en|de/}
                                 answer GET    (/:locale)/answers/:id(.:format)                                 answers#show {:locale=>/en|de/}
                                        PUT    (/:locale)/answers/:id(.:format)                                 answers#update {:locale=>/en|de/}
                                        DELETE (/:locale)/answers/:id(.:format)                                 answers#destroy {:locale=>/en|de/}
                        group_questions GET    (/:locale)/groups/:group_id/questions(.:format)                  questions#index {:locale=>/en|de/}
                                        POST   (/:locale)/groups/:group_id/questions(.:format)                  questions#create {:locale=>/en|de/}
                     new_group_question GET    (/:locale)/groups/:group_id/questions/new(.:format)              questions#new {:locale=>/en|de/}
                          edit_question GET    (/:locale)/questions/:id/edit(.:format)                          questions#edit {:locale=>/en|de/}
                               question GET    (/:locale)/questions/:id(.:format)                               questions#show {:locale=>/en|de/}
                                        PUT    (/:locale)/questions/:id(.:format)                               questions#update {:locale=>/en|de/}
                                        DELETE (/:locale)/questions/:id(.:format)                               questions#destroy {:locale=>/en|de/}
                                 groups GET    (/:locale)/groups(.:format)                                      groups#index {:locale=>/en|de/}
                                        POST   (/:locale)/groups(.:format)                                      groups#create {:locale=>/en|de/}
                              new_group GET    (/:locale)/groups/new(.:format)                                  groups#new {:locale=>/en|de/}
                             edit_group GET    (/:locale)/groups/:id/edit(.:format)                             groups#edit {:locale=>/en|de/}
                                  group GET    (/:locale)/groups/:id(.:format)                                  groups#show {:locale=>/en|de/}
                                        PUT    (/:locale)/groups/:id(.:format)                                  groups#update {:locale=>/en|de/}
                                        DELETE (/:locale)/groups/:id(.:format)                                  groups#destroy {:locale=>/en|de/}
                    membership_requests GET    (/:locale)/membership_requests(.:format)                         membership_requests#index {:locale=>/en|de/}
                                        POST   (/:locale)/membership_requests(.:format)                         membership_requests#create {:locale=>/en|de/}
                     membership_request DELETE (/:locale)/membership_requests/:id(.:format)                     membership_requests#destroy {:locale=>/en|de/}
              create_membership_request POST   (/:locale)/membership_requests/create(.:format)                  membership_requests#create {:locale=>/en|de/}
             confirm_membership_request        (/:locale)/membership_requests/:id/confirm(.:format)             membership_requests#confirm {:locale=>/en|de/}
              reject_membership_request        (/:locale)/membership_requests/:id/reject(.:format)              membership_requests#reject {:locale=>/en|de/}
       add_as_member_membership_request        (/:locale)/membership_requests/:id/add_as_member(.:format)       membership_requests#add_as_member {:locale=>/en|de/}
                       new_user_session GET    (/:locale)/users/sign_in(.:format)                               users/sessions#new {:locale=>/en|de/}
                           user_session POST   (/:locale)/users/sign_in(.:format)                               users/sessions#create {:locale=>/en|de/}
                   destroy_user_session DELETE (/:locale)/users/sign_out(.:format)                              users/sessions#destroy {:locale=>/en|de/}
                          user_password POST   (/:locale)/users/password(.:format)                              devise/passwords#create {:locale=>/en|de/}
                      new_user_password GET    (/:locale)/users/password/new(.:format)                          devise/passwords#new {:locale=>/en|de/}
                     edit_user_password GET    (/:locale)/users/password/edit(.:format)                         devise/passwords#edit {:locale=>/en|de/}
                                        PUT    (/:locale)/users/password(.:format)                              devise/passwords#update {:locale=>/en|de/}
               cancel_user_registration GET    (/:locale)/users/cancel(.:format)                                users/registrations#cancel {:locale=>/en|de/}
                      user_registration POST   (/:locale)/users(.:format)                                       users/registrations#create {:locale=>/en|de/}
                  new_user_registration GET    (/:locale)/users/sign_up(.:format)                               users/registrations#new {:locale=>/en|de/}
                 edit_user_registration GET    (/:locale)/users/edit(.:format)                                  users/registrations#edit {:locale=>/en|de/}
                                        PUT    (/:locale)/users(.:format)                                       users/registrations#update {:locale=>/en|de/}
                                        DELETE (/:locale)/users(.:format)                                       users/registrations#destroy {:locale=>/en|de/}
                      user_confirmation POST   (/:locale)/users/confirmation(.:format)                          users/confirmations#create {:locale=>/en|de/}
                  new_user_confirmation GET    (/:locale)/users/confirmation/new(.:format)                      users/confirmations#new {:locale=>/en|de/}
                                        GET    (/:locale)/users/confirmation(.:format)                          users/confirmations#show {:locale=>/en|de/}
                              feedbacks GET    (/:locale)/feedbacks(.:format)                                   feedbacks#index {:locale=>/en|de/}
                                        POST   (/:locale)/feedbacks(.:format)                                   feedbacks#create {:locale=>/en|de/}
                           new_feedback GET    (/:locale)/feedbacks/new(.:format)                               feedbacks#new {:locale=>/en|de/}
                          edit_feedback GET    (/:locale)/feedbacks/:id/edit(.:format)                          feedbacks#edit {:locale=>/en|de/}
                               feedback GET    (/:locale)/feedbacks/:id(.:format)                               feedbacks#show {:locale=>/en|de/}
                                        PUT    (/:locale)/feedbacks/:id(.:format)                               feedbacks#update {:locale=>/en|de/}
                                        DELETE (/:locale)/feedbacks/:id(.:format)                               feedbacks#destroy {:locale=>/en|de/}
                  mark_feedback_as_read POST   (/:locale)/feedbacks/:id/mark_as_read(.:format)                  feedbacks#mark_as_read {:locale=>/en|de/}
              mark_notification_as_read POST   (/:locale)/notifications/:id/mark_as_read(.:format)              notifications#mark_as_read {:locale=>/en|de/}
                                mathjax        (/:locale)/mathjax/*uri(.:format)                                MathjaxRails#giveOutStaticFile {:locale=>/en|de/}
                         email_settings GET    (/:locale)/email_settings(.:format)                              email_settings#index {:locale=>/en|de/}
                                        POST   (/:locale)/email_settings(.:format)                              email_settings#create {:locale=>/en|de/}
                      new_email_setting GET    (/:locale)/email_settings/new(.:format)                          email_settings#new {:locale=>/en|de/}
                     edit_email_setting GET    (/:locale)/email_settings/:id/edit(.:format)                     email_settings#edit {:locale=>/en|de/}
                          email_setting GET    (/:locale)/email_settings/:id(.:format)                          email_settings#show {:locale=>/en|de/}
                                        PUT    (/:locale)/email_settings/:id(.:format)                          email_settings#update {:locale=>/en|de/}
                                        DELETE (/:locale)/email_settings/:id(.:format)                          email_settings#destroy {:locale=>/en|de/}
change_email_settings_for_subscriptions        (/:locale)/email_settings/subscriptions(.:format)                email_settings#change_emails_for_subscriptions {:locale=>/en|de/}
                           ajax_courses GET    (/:locale)/ajax/courses(.:format)                                ajax#courses {:locale=>/en|de/}
                          ajax_lectures GET    (/:locale)/ajax/lectures(.:format)                               ajax#lectures {:locale=>/en|de/}
                            ajax_chairs GET    (/:locale)/ajax/chairs(.:format)                                 ajax#chairs {:locale=>/en|de/}
                                  intro        (/:locale)/intro(.:format)                                       landing_page#index {:locale=>/en|de/}
                                   home        (/:locale)/home(.:format)                                        home#index {:locale=>/en|de/}
                           my_faculties        (/:locale)/my_faculties(.:format)                                my_faculties#index {:locale=>/en|de/}
                      permission_denied        (/:locale)/permission_denied(.:format)                           applications#permission_denied {:locale=>/en|de/}
                          notifications GET    (/:locale)/notifications(.:format)                               notifications#index {:locale=>/en|de/}
                                        POST   (/:locale)/notifications(.:format)                               notifications#create {:locale=>/en|de/}
                       new_notification GET    (/:locale)/notifications/new(.:format)                           notifications#new {:locale=>/en|de/}
                      edit_notification GET    (/:locale)/notifications/:id/edit(.:format)                      notifications#edit {:locale=>/en|de/}
                           notification GET    (/:locale)/notifications/:id(.:format)                           notifications#show {:locale=>/en|de/}
                                        PUT    (/:locale)/notifications/:id(.:format)                           notifications#update {:locale=>/en|de/}
                                        DELETE (/:locale)/notifications/:id(.:format)                           notifications#destroy {:locale=>/en|de/}
                              faculties GET    (/:locale)/faculties(.:format)                                   faculties#index {:locale=>/en|de/}
                                        POST   (/:locale)/faculties(.:format)                                   faculties#create {:locale=>/en|de/}
                            new_faculty GET    (/:locale)/faculties/new(.:format)                               faculties#new {:locale=>/en|de/}
                           edit_faculty GET    (/:locale)/faculties/:id/edit(.:format)                          faculties#edit {:locale=>/en|de/}
                                faculty GET    (/:locale)/faculties/:id(.:format)                               faculties#show {:locale=>/en|de/}
                                        PUT    (/:locale)/faculties/:id(.:format)                               faculties#update {:locale=>/en|de/}
                                        DELETE (/:locale)/faculties/:id(.:format)                               faculties#destroy {:locale=>/en|de/}
                                  terms GET    (/:locale)/terms(.:format)                                       terms#index {:locale=>/en|de/}
                                        POST   (/:locale)/terms(.:format)                                       terms#create {:locale=>/en|de/}
                               new_term GET    (/:locale)/terms/new(.:format)                                   terms#new {:locale=>/en|de/}
                              edit_term GET    (/:locale)/terms/:id/edit(.:format)                              terms#edit {:locale=>/en|de/}
                                   term GET    (/:locale)/terms/:id(.:format)                                   terms#show {:locale=>/en|de/}
                                        PUT    (/:locale)/terms/:id(.:format)                                   terms#update {:locale=>/en|de/}
                                        DELETE (/:locale)/terms/:id(.:format)                                   terms#destroy {:locale=>/en|de/}
                         search_courses GET    (/:locale)/courses/search(.:format)                              terms#search_courses {:locale=>/en|de/}
                      search_my_courses GET    (/:locale)/my_courses/search(.:format)                           terms#search_courses {:locale=>/en|de/}
                 search_courses_in_term GET    (/:locale)/terms/:id/search(.:format)                            terms#search_courses {:locale=>/en|de/}
                        search_lectures GET    (/:locale)/lectures/search(.:format)                             lectures#search {:locale=>/en|de/}
                                 search GET    (/:locale)/search(.:format)                                      search#index {:locale=>/en|de/}
                       users_moderation GET    (/:locale)/users/moderation(.:format)                            users#moderation {:locale=>/en|de/}
                           search_users GET    (/:locale)/users/moderation/search(.:format)                     users#search {:locale=>/en|de/}
                                  users GET    (/:locale)/users(.:format)                                       users#index {:locale=>/en|de/}
                                        POST   (/:locale)/users(.:format)                                       users#create {:locale=>/en|de/}
                               new_user GET    (/:locale)/users/new(.:format)                                   users#new {:locale=>/en|de/}
                              edit_user GET    (/:locale)/users/:id/edit(.:format)                              users#edit {:locale=>/en|de/}
                                   user GET    (/:locale)/users/:id(.:format)                                   users#show {:locale=>/en|de/}
                                        PUT    (/:locale)/users/:id(.:format)                                   users#update {:locale=>/en|de/}
                                        DELETE (/:locale)/users/:id(.:format)                                   users#destroy {:locale=>/en|de/}
                        users_questions GET    (/:locale)/users/:id/questions(.:format)                         users#questions {:locale=>/en|de/}
                          users_answers GET    (/:locale)/users/:id/answers(.:format)                           users#answers {:locale=>/en|de/}
                           confirm_user        (/:locale)/users/:id/confirm(.:format)                           users#confirm {:locale=>/en|de/}
                       mark_all_as_read POST   (/:locale)/notifications/mark_all_as_read(.:format)              notifications#mark_all_as_read {:locale=>/en|de/}
               delete_all_notifications POST   (/:locale)/notifications/delete_all_notifications(.:format)      notifications#delete_all_notifications {:locale=>/en|de/}
               notifications_for_course        (/:locale)/notifications(.:format)                               notifications#index {:locale=>/en|de/}
               comment_course_recording POST   (/:locale)/courses/:course_id/recordings/:id/comment(.:format)   recordings#comment {:locale=>/en|de/}
                      course_recordings GET    (/:locale)/courses/:course_id/recordings(.:format)               recordings#index {:locale=>/en|de/}
                                        POST   (/:locale)/courses/:course_id/recordings(.:format)               recordings#create {:locale=>/en|de/}
                   new_course_recording GET    (/:locale)/courses/:course_id/recordings/new(.:format)           recordings#new {:locale=>/en|de/}
                  edit_course_recording GET    (/:locale)/courses/:course_id/recordings/:id/edit(.:format)      recordings#edit {:locale=>/en|de/}
                       course_recording GET    (/:locale)/courses/:course_id/recordings/:id(.:format)           recordings#show {:locale=>/en|de/}
                                        PUT    (/:locale)/courses/:course_id/recordings/:id(.:format)           recordings#update {:locale=>/en|de/}
                                        DELETE (/:locale)/courses/:course_id/recordings/:id(.:format)           recordings#destroy {:locale=>/en|de/}
                                courses GET    (/:locale)/courses(.:format)                                     courses#index {:locale=>/en|de/}
                                        POST   (/:locale)/courses(.:format)                                     courses#create {:locale=>/en|de/}
                             new_course GET    (/:locale)/courses/new(.:format)                                 courses#new {:locale=>/en|de/}
                            edit_course GET    (/:locale)/courses/:id/edit(.:format)                            courses#edit {:locale=>/en|de/}
                                 course GET    (/:locale)/courses/:id(.:format)                                 courses#show {:locale=>/en|de/}
                                        PUT    (/:locale)/courses/:id(.:format)                                 courses#update {:locale=>/en|de/}
                                        DELETE (/:locale)/courses/:id(.:format)                                 courses#destroy {:locale=>/en|de/}
                           manage_users        (/:locale)/courses/:id/manage_users(.:format)                    courses#manage_users {:locale=>/en|de/}
                   course_announcements        (/:locale)/courses/:id/announcements(.:format)                   courses#announcements {:locale=>/en|de/}
                 search_users_to_manage        (/:locale)/courses/:id/search_users(.:format)                    courses#search_users {:locale=>/en|de/}
                         courses_search        (/:locale)/courses/search(.:format)                              courses#search {:locale=>/en|de/}
                          follow_course        (/:locale)/courses/:id/following(.:format)                       courses#following {:locale=>/en|de/}
                         approve_course        (/:locale)/courses/:id/approve(.:format)                         courses#approve {:locale=>/en|de/}
                                               (/:locale)/courses/:id/unfollow(.:format)                        courses#following {:locale=>/en|de/, :unfollow=>"true"}
                     maintainer_request        (/:locale)/posts/maintainer_request(.:format)                    posts#maintainer_request {:locale=>/en|de/}
                           convert_post POST   (/:locale)/posts/:id/convert(.:format)                           posts#convert {:locale=>/en|de/}
                              rate_post        (/:locale)/posts/:id/rate(.:format)                              posts#rate {:locale=>/en|de/}
                          answered_post        (/:locale)/posts/:id/answered(.:format)                          posts#answered {:locale=>/en|de/}
                                               (/:locale)/posts/:parent_id/answering(.:format)                  posts#answering {:locale=>/en|de/}
                                               (/:locale)/posts/:parent_id/commenting(.:format)                 posts#commenting {:locale=>/en|de/}
                                reports GET    (/:locale)/reports(.:format)                                     reports#index {:locale=>/en|de/}
                                        POST   (/:locale)/reports(.:format)                                     reports#create {:locale=>/en|de/}
                             new_report GET    (/:locale)/reports/new(.:format)                                 reports#new {:locale=>/en|de/}
                            edit_report GET    (/:locale)/reports/:id/edit(.:format)                            reports#edit {:locale=>/en|de/}
                                 report GET    (/:locale)/reports/:id(.:format)                                 reports#show {:locale=>/en|de/}
                                        PUT    (/:locale)/reports/:id(.:format)                                 reports#update {:locale=>/en|de/}
                                        DELETE (/:locale)/reports/:id(.:format)                                 reports#destroy {:locale=>/en|de/}
                    mark_report_as_read        (/:locale)/reports/:id/mark_read(.:format)                       reports#mark_read {:locale=>/en|de/}
                     course_memberships GET    (/:locale)/course_memberships(.:format)                          course_memberships#index {:locale=>/en|de/}
                                        POST   (/:locale)/course_memberships(.:format)                          course_memberships#create {:locale=>/en|de/}
                  new_course_membership GET    (/:locale)/course_memberships/new(.:format)                      course_memberships#new {:locale=>/en|de/}
                 edit_course_membership GET    (/:locale)/course_memberships/:id/edit(.:format)                 course_memberships#edit {:locale=>/en|de/}
                      course_membership GET    (/:locale)/course_memberships/:id(.:format)                      course_memberships#show {:locale=>/en|de/}
                                        PUT    (/:locale)/course_memberships/:id(.:format)                      course_memberships#update {:locale=>/en|de/}
                                        DELETE (/:locale)/course_memberships/:id(.:format)                      course_memberships#destroy {:locale=>/en|de/}
                             my_courses        (/:locale)/my_courses(.:format)                                  course_memberships#index {:locale=>/en|de/}
                          search_chairs GET    (/:locale)/chairs/search(.:format)                               chairs#search {:locale=>/en|de/}
                                 chairs GET    (/:locale)/chairs(.:format)                                      chairs#index {:locale=>/en|de/}
                                        POST   (/:locale)/chairs(.:format)                                      chairs#create {:locale=>/en|de/}
                              new_chair GET    (/:locale)/chairs/new(.:format)                                  chairs#new {:locale=>/en|de/}
                             edit_chair GET    (/:locale)/chairs/:id/edit(.:format)                             chairs#edit {:locale=>/en|de/}
                                  chair GET    (/:locale)/chairs/:id(.:format)                                  chairs#show {:locale=>/en|de/}
                                        PUT    (/:locale)/chairs/:id(.:format)                                  chairs#update {:locale=>/en|de/}
                                        DELETE (/:locale)/chairs/:id(.:format)                                  chairs#destroy {:locale=>/en|de/}
        autocomplete_courses_name_posts GET    (/:locale)/posts/autocomplete_courses_name(.:format)             posts#autocomplete_courses_name {:locale=>/en|de/}
                                  posts GET    (/:locale)/posts(.:format)                                       posts#index {:locale=>/en|de/}
                                        POST   (/:locale)/posts(.:format)                                       posts#create {:locale=>/en|de/}
                               new_post GET    (/:locale)/posts/new(.:format)                                   posts#new {:locale=>/en|de/}
                              edit_post GET    (/:locale)/posts/:id/edit(.:format)                              posts#edit {:locale=>/en|de/}
                                   post GET    (/:locale)/posts/:id(.:format)                                   posts#show {:locale=>/en|de/}
                                        PUT    (/:locale)/posts/:id(.:format)                                   posts#update {:locale=>/en|de/}
                                        DELETE (/:locale)/posts/:id(.:format)                                   posts#destroy {:locale=>/en|de/}
                                        GET    (/:locale)/reports(.:format)                                     reports#index {:locale=>/en|de/}
                                        POST   (/:locale)/reports(.:format)                                     reports#create {:locale=>/en|de/}
                                        GET    (/:locale)/reports/new(.:format)                                 reports#new {:locale=>/en|de/}
                                        GET    (/:locale)/reports/:id/edit(.:format)                            reports#edit {:locale=>/en|de/}
                                        GET    (/:locale)/reports/:id(.:format)                                 reports#show {:locale=>/en|de/}
                                        PUT    (/:locale)/reports/:id(.:format)                                 reports#update {:locale=>/en|de/}
                                        DELETE (/:locale)/reports/:id(.:format)                                 reports#destroy {:locale=>/en|de/}
                                periods GET    (/:locale)/periods(.:format)                                     periods#index {:locale=>/en|de/}
                                        POST   (/:locale)/periods(.:format)                                     periods#create {:locale=>/en|de/}
                             new_period GET    (/:locale)/periods/new(.:format)                                 periods#new {:locale=>/en|de/}
                            edit_period GET    (/:locale)/periods/:id/edit(.:format)                            periods#edit {:locale=>/en|de/}
                                 period GET    (/:locale)/periods/:id(.:format)                                 periods#show {:locale=>/en|de/}
                                        PUT    (/:locale)/periods/:id(.:format)                                 periods#update {:locale=>/en|de/}
                                        DELETE (/:locale)/periods/:id(.:format)                                 periods#destroy {:locale=>/en|de/}
                             institutes GET    (/:locale)/institutes(.:format)                                  institutes#index {:locale=>/en|de/}
                                        POST   (/:locale)/institutes(.:format)                                  institutes#create {:locale=>/en|de/}
                          new_institute GET    (/:locale)/institutes/new(.:format)                              institutes#new {:locale=>/en|de/}
                         edit_institute GET    (/:locale)/institutes/:id/edit(.:format)                         institutes#edit {:locale=>/en|de/}
                              institute GET    (/:locale)/institutes/:id(.:format)                              institutes#show {:locale=>/en|de/}
                                        PUT    (/:locale)/institutes/:id(.:format)                              institutes#update {:locale=>/en|de/}
                                        DELETE (/:locale)/institutes/:id(.:format)                              institutes#destroy {:locale=>/en|de/}
                                 events GET    (/:locale)/events(.:format)                                      events#index {:locale=>/en|de/}
                                        POST   (/:locale)/events(.:format)                                      events#create {:locale=>/en|de/}
                              new_event GET    (/:locale)/events/new(.:format)                                  events#new {:locale=>/en|de/}
                             edit_event GET    (/:locale)/events/:id/edit(.:format)                             events#edit {:locale=>/en|de/}
                                  event GET    (/:locale)/events/:id(.:format)                                  events#show {:locale=>/en|de/}
                                        PUT    (/:locale)/events/:id(.:format)                                  events#update {:locale=>/en|de/}
                                        DELETE (/:locale)/events/:id(.:format)                                  events#destroy {:locale=>/en|de/}
                               lectures GET    (/:locale)/lectures(.:format)                                    lectures#index {:locale=>/en|de/}
                                        POST   (/:locale)/lectures(.:format)                                    lectures#create {:locale=>/en|de/}
                            new_lecture GET    (/:locale)/lectures/new(.:format)                                lectures#new {:locale=>/en|de/}
                           edit_lecture GET    (/:locale)/lectures/:id/edit(.:format)                           lectures#edit {:locale=>/en|de/}
                                lecture GET    (/:locale)/lectures/:id(.:format)                                lectures#show {:locale=>/en|de/}
                                        PUT    (/:locale)/lectures/:id(.:format)                                lectures#update {:locale=>/en|de/}
                                        DELETE (/:locale)/lectures/:id(.:format)                                lectures#destroy {:locale=>/en|de/}
                                   root        /(:locale)(.:format)                                             landing_page#index {:locale=>/en|de/}
                                               /*path(.:format)                                                 :controller#:action
                                               /                                                                :controller#:action
